import type { Program } from "./types";

export const mockPrograms: Program[] = [
  { id: 1, university_name: "The University of Hong Kong", program_name: "HKU MSc Business Analytics", country: "Hong Kong", field: "Business Analytics", degree_type: "MSc", application_deadline: "2026-12-01", tuition_amount: 396000, tuition_currency: "HKD", ielts_requirement: "7.0", toefl_requirement: "100", gre_required: false, gmat_required: false, extraction_confidence: 0.86, review_status: "auto_extracted", source_url: "https://www.hku.hk/msc-business-analytics", raw_text_snapshot: "Demo raw text snapshot. Verify with official website before applying." },
  { id: 2, university_name: "National University of Singapore", program_name: "NUS MSc Business Analytics", country: "Singapore", field: "Business Analytics", degree_type: "MSc", application_deadline: "2026-11-30", tuition_amount: 65000, tuition_currency: "SGD", ielts_requirement: "7.0", toefl_requirement: "100", gre_required: false, gmat_required: false, extraction_confidence: 0.88, review_status: "auto_extracted", source_url: "https://www.nus.edu.sg/msc-business-analytics" },
  { id: 3, university_name: "The Chinese University of Hong Kong", program_name: "CUHK MSc Finance", country: "Hong Kong", field: "Finance", degree_type: "MSc", application_deadline: "2027-01-15", tuition_amount: 420000, tuition_currency: "HKD", ielts_requirement: "6.5", toefl_requirement: "90", gre_required: false, gmat_required: false, extraction_confidence: 0.82, review_status: "auto_extracted", source_url: "https://www.cuhk.edu.hk/msc-finance" },
  { id: 4, university_name: "University College London", program_name: "UCL MSc Management", country: "United Kingdom", field: "Management", degree_type: "MSc", application_deadline: "2027-03-31", tuition_amount: 38300, tuition_currency: "GBP", ielts_requirement: "7.0", toefl_requirement: "100", gre_required: false, gmat_required: false, extraction_confidence: 0.84, review_status: "auto_extracted", source_url: "https://www.ucl.ac.uk/msc-management" },
  { id: 5, university_name: "Imperial College London", program_name: "Imperial MSc Strategic Marketing", country: "United Kingdom", field: "Marketing", degree_type: "MSc", application_deadline: "2027-02-15", tuition_amount: 41000, tuition_currency: "GBP", ielts_requirement: "7.0", toefl_requirement: "100", gre_required: false, gmat_required: false, extraction_confidence: 0.81, review_status: "auto_extracted", source_url: "https://www.imperial.ac.uk/msc-strategic-marketing" },
  { id: 6, university_name: "University of Manchester", program_name: "University of Manchester MSc Business Analytics", country: "United Kingdom", field: "Business Analytics", degree_type: "MSc", application_deadline: "2027-01-05", tuition_amount: 31000, tuition_currency: "GBP", ielts_requirement: "7.0", toefl_requirement: "100", gre_required: false, gmat_required: false, extraction_confidence: 0.87, review_status: "auto_extracted", source_url: "https://www.manchester.ac.uk/msc-business-analytics" }
];
